<img src="Letters.png" width=324 height=332 />

In [4]:
burti = [
    ['A',[0,1,0,1,0,1,1,1,1,1,0,1,1,0,1],[1,0,0]],
    ['E',[1,1,1,1,0,0,1,1,0,1,0,0,1,1,1],[1,0,0]],
    ['D',[1,1,0,1,0,1,1,0,1,1,0,1,1,1,0],[1,0,0]],
    ['B',[1,1,0,1,0,1,1,1,0,1,0,1,1,1,0],[0,1,0]],
    ['C',[1,1,1,1,0,0,1,0,0,1,0,0,1,1,1],[0,1,0]],
    ['F',[1,1,1,1,0,0,1,1,0,1,0,0,1,0,0],[0,1,0]],
    ['G',[1,1,1,1,0,0,1,0,1,1,0,1,1,1,1],[0,0,1]],
    ['H',[1,0,1,1,0,1,1,1,1,1,0,1,1,0,1],[0,0,1]],
    ['I',[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],[0,0,1]]
]

In [5]:
print(burti)

[['A', [0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1], [1, 0, 0]], ['E', [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1], [1, 0, 0]], ['D', [1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0], [1, 0, 0]], ['B', [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0], [0, 1, 0]], ['C', [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1], [0, 1, 0]], ['F', [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0], [0, 1, 0]], ['G', [1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1], [0, 0, 1]], ['H', [1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1], [0, 0, 1]], ['I', [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0], [0, 0, 1]]]


In [6]:
import numpy as np

lc = 0.1  #Apmācības koeficients

class Neirons:
    
    def __init__(self, inSize):
        self.w = np.zeros(inSize)
        self.w0 = 0
    
    def classify(self, x):
        net = np.dot(x, self.w)
        net += self.w0
        y = 0 if net < 0 else 1
        return y
    
    def learn(self, x, z):
        y = self.classify(x)
        delta = z-y
        if delta != 0:
            for i in range(0, len(self.w)):
                self.w[i]+= lc * delta * x[i]
            self.w0+= lc * delta

In [7]:
n1 = Neirons(15);
n2 = Neirons(15);
n3 = Neirons(15);
# print(n1.classify(burti[0][1]))

for eph in range(0, 100):
    for bi in range(0, len(burti)):
        n1.learn(burti[bi][1], burti[bi][2][0])
        n2.learn(burti[bi][1], burti[bi][2][1])
        n3.learn(burti[bi][1], burti[bi][2][2])

for bi in range(0, len(burti)):
    print(
        burti[bi][0]+" "
        +str(n1.classify(burti[bi][1]))+" "
        +str(n2.classify(burti[bi][1]))+" "
        +str(n3.classify(burti[bi][1]))
    )
    


A 1 0 0
E 1 0 0
D 1 0 0
B 0 1 0
C 0 1 0
F 0 1 0
G 0 0 1
H 0 0 1
I 0 0 1


In [8]:
print(n1.w)
print(n2.w)
print(n3.w)

[-0.6  0.4 -0.7  0.  -0.5 -0.2  0.   0.9  1.8  0.  -0.5 -1.1  0.   0.2
  0.3]
[ 0.3  0.  -0.3  0.2 -0.3  0.4  0.2 -0.4 -1.4  0.2 -0.3 -0.1  0.2  0.1
 -0.4]
[ 0.2 -0.3  0.3 -0.2  0.3 -0.1 -0.2 -0.2  0.4 -0.2  0.3  0.4 -0.2  0.1
 -0.1]


In [9]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [12]:
import tensorflow as tf
#  from keras.layers import Dense
#  from keras.models import Sequential

model = tf.keras.models.Sequential()  #izveidot tukšu modeli
model.add(
    tf.keras.layers.Dense(3, activation='softmax', input_shape = (len(iris.data[0]), ))
)  #Pievienot vienu slāni ar 3 neironiem, "softmax" aktivācijas funkciju un norādot ieejas signāla garumu (4)

model.compile(tf.optimizers.RMSprop(0.001), loss='mse')  #Pabeigt modeļa izveidi.
# Izmatot optimizatoru RMSprop ar apmācības ātrumu 0,001.
# Izmantot vidējo kvadrātisko kļūdu.

# Izveidot jaunu "pareizo" vērtību masīvu no iris masīva, nomainot saturu no [0,1,2...] uz [[1,0,0],[0,1,0],[0,0,1]..]
targets = np.zeros((len(iris.target),3))  #Izveidot 150x3 lielu masīvu un aizpildīt ar nullēm
for ti in range(0, len(iris.target)):
    if iris.target[ti] == 0:
        targets[ti][0] = 1
    elif iris.target[ti] == 1:
        targets[ti][1] = 1
    else:
        targets[ti][2] = 1
print(targets)
print(iris.data)
model.fit(iris.data, targets, epochs=300)  #Veikt apmācību

predictions = model.predict(iris.data)  #Iegū klašu piederības vērtības datiem



[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [11]:
for di in range(0, len(iris.data)):
    print(
        str(iris.data[di][0])+"\t"+
        str(iris.data[di][1])+"\t"+
        str(iris.data[di][2])+"\t"+
        str(iris.data[di][3])+"\t"+
        str(targets[di][0])+"\t"+
        str(targets[di][1])+"\t"+
        str(targets[di][2])+"\t"+
        str(predictions[di][0])+"\t"+
        str(predictions[di][1])+"\t"+
        str(predictions[di][2])
    )


5.1	3.5	1.4	0.2	1.0	0.0	0.0	0.8774406	0.1225593	1.0287184e-07
4.9	3.0	1.4	0.2	1.0	0.0	0.0	0.8214842	0.17851548	3.131519e-07
4.7	3.2	1.3	0.2	1.0	0.0	0.0	0.8536941	0.14630562	3.4332362e-07
4.6	3.1	1.5	0.2	1.0	0.0	0.0	0.80916023	0.19083938	3.8068464e-07
5.0	3.6	1.4	0.2	1.0	0.0	0.0	0.88412184	0.115878046	1.01961454e-07
5.4	3.9	1.7	0.4	1.0	0.0	0.0	0.8961626	0.10383744	1.910517e-08
4.6	3.4	1.4	0.3	1.0	0.0	0.0	0.8662486	0.1337512	2.2949446e-07
5.0	3.4	1.5	0.2	1.0	0.0	0.0	0.85311645	0.14688338	1.2757684e-07
4.4	2.9	1.4	0.2	1.0	0.0	0.0	0.795224	0.20477527	7.8896545e-07
4.9	3.1	1.5	0.1	1.0	0.0	0.0	0.80660546	0.19339423	2.731646e-07
5.4	3.7	1.5	0.2	1.0	0.0	0.0	0.8883453	0.11165469	4.2225977e-08
4.8	3.4	1.6	0.2	1.0	0.0	0.0	0.8339301	0.16606967	1.564671e-07
4.8	3.0	1.4	0.1	1.0	0.0	0.0	0.80833876	0.1916609	4.1510145e-07
4.3	3.0	1.1	0.1	1.0	0.0	0.0	0.8430769	0.15692197	1.2283176e-06
5.8	4.0	1.2	0.2	1.0	0.0	0.0	0.93814445	0.06185559	1.8372491e-08
5.7	4.4	1.5	0.4	1.0	0.0	0.0	0.9445517	0.05544831	6.2948